### ISSUE TITLE
Hotjar 

### ISSUE THREAD

**Issue by michaelschofield** [fontana-regional-library/frl#27]

**Comment by amy-actually** [comment]
I 're-installed' hotjar via the drupal module rather than template (it wasn't collecting any data from the staff portal due to login). I added a heatmap previously just to test [feel free to reconfigure as needed] - so I'll keep an eye out to be sure it's working (and that the public site is still capturing after the switch).

**Comment by michaelschofield** [comment]
@awestlib Awesome! Great thinking.
